### PR TITLE
Conduits with multiple concurrency join points

### PR DESCRIPTION
**Pull request by rjmac**
Introduces the =$=&, $=&, =$& operators to complement $$&.  Implements
the suggestion in #31.

### CODE REVIEW

**Comment by rjmac** [comment]
"The Glorious Glasgow Haskell Compilation System, version 7.6.3" ...oh bleh, I'm too up-to-date.  The travis build doesn't like type families!

**Comment by cgaebel** [comment]
Can you make it work with both?

**Comment by rjmac** [comment]
Thinking about it.  In the worst case I can just give up the nice "`$$&` and `$=&` are the only combinators you'll need" property and make calling code use a different set if it includes a buffer-to-file stage.  That wouldn't be the worst thing in the world; I might've gotten too cute with the overloading.

**Comment by cgaebel** [comment]
That sounds good to me. Also a comment summarizing each function would be nice, too. :)

**Comment by qnikst** [comment]
doesn't functional dependencies work here on ghc-7.8?

**Comment by rjmac** [comment]
You're absolutely right, fundeps are sufficient.  I've got that implemented and tested (albeit in 7.8 only still).  I'll update the pull request tonight or tomorrow, after I've given it a try in 7.6 and written those comments you asked for,

**Pull request merged**
